name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!