name: Prod workflow

on:
  create:
    tags:
      - v*-qa

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "QA: Hello, world!"