name: QA workflow

on:
  push:
    tags:
      - 'v*-qa'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "QA Hello, world!"
    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/} | sed 's,/,-,g')"
      id: extract_tag
    - run: echo ${{ steps.extract_tag.outputs.tag }}